[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.coverage.html]
skip_empty = true
show_contexts = true

[tool.black]
line-length = 120
target-version = ['py38']

